export const GET_THEME_WEB_FILTERS_SUCCESS = "GET_THEME_WEB_FILTERS_SUCCESS";
export const GET_THEME_WEB_FILTERS_ERROR = "GET_THEME_WEB_FILTERS_ERROR";
export const GET_LOADER_ERROR = "GET_LOADER_ERROR";
export const GET_LOADER_SUCCESS = "GET_LOADER_SUCCESS";
/* trial purpose for optimization */ 
/* export const GET_ANNOUNCEMENTS_SUCCESS = "GET_ANNOUNCEMENTS_SUCCESS";*/
/*export const GET_ANNOUNCEMENTS_ERROR = "GET_ANNOUNCEMENTS_ERROR";*/
export const GET_WALL_SUCCESS = "GET_WALL_SUCCESS";
export const GET_WALL_ERROR = "GET_WALL_ERROR";
export const GET_POST_DATA_SUCCESS = "GET_POST_DATA_SUCCESS";
export const GET_POST_DATA_ERROR = "GET_POST_DATA_ERROR";
export const GET_CUSTOM_POST_DATA_SUCCESS = "GET_CUSTOM_POST_DATA_SUCCESS";
export const GET_CUSTOM_POST_DATA_ERROR = "GET_CUSTOM_POST_DATA_ERROR";
export const GET_THEME_ERROR_SUCCESS = "GET_THEME_ERROR_SUCCESS";
export const GET_WALL_ID_SUCCESS = "GET_WALL_ID_SUCCESS";
export const GET_WALL_ID_ERROR = "GET_WALL_ID_ERROR";
export const GET_THEME_LOADER_SUCCESS = "GET_THEME_LOADER_SUCCESS";
export const GET_LANGUAGE_SUCCESS = "GET_LANGUAGE_SUCCESS";
export const GET_FILTERED_POST_DATA_ERROR = "GET_FILTERED_POST_DATA_ERROR";
export const GET_FILTERED_POST_DATA_SUCCESS = "GET_FILTERED_POST_DATA_SUCCESS";
export const GET_DATA_POST_APPEND_KEY = "GET_DATA_POST_APPEND_KEY";
export const GET_APPEND_DATA_SUCCESS = "GET_APPEND_DATA_SUCCESS";
/* trial purpose for optimization */ 
/*export const GET_APPEND_DATA__ERROR = "GET_APPEND_DATA__ERROR";*/
export const GET_BUTTON_NAME_UPDATE_SUCCESS = "GET_BUTTON_NAME_UPDATE_SUCCESS";
export const GET_NETWORK_ID_APPEND_DATA_SUCCESS = "GET_NETWORK_ID_APPEND_DATA_SUCCESS";
export const GET_THEME_SHOW_MORE_LOADER_SUCCESS = "GET_THEME_SHOW_MORE_LOADER_SUCCESS";
export const GET_IFRAME_EVENT_SUCCESS = "GET_IFRAME_EVENT_SUCCESS";
export const GET_WEB_FILTER_LOADER_SUCCESS = "GET_WEB_FILTER_LOADER_SUCCESS";
export const GET_HORIZONTAL_POST_DATA_SUCCESS = "GET_HORIZONTAL_POST_DATA_SUCCESS";
export const GET_PRE_RENDER_POST_DATA_SUCCESS = "GET_PRE_RENDER_POST_DATA_SUCCESS";
export const GET_FILTERED_COMPLETE_POST_DATA_SUCCESS = "GET_FILTERED_COMPLETE_POST_DATA_SUCCESS";
/* trial purpose for optimization */ 
/*export const GET_CURRENT_FILTER_ID = 'GET_CURRENT_FILTER_ID'; */
export const GET_THEME_DATA_SUCCESS = 'GET_THEME_DATA_SUCCESS';
export const GET_THEME_DATA_ERROR = 'GET_THEME_DATA_ERROR';
export const SET_HAS_MORE_DATA = 'SET_HAS_MORE_DATA';
export const SET_FILTER_ALL = 'SET_FILTER_ALL'

export const SET_URLS_ACCESSED_FOR_DATA = 'SET_URLS_ACCESSED_FOR_DATA';
/* trial purpose for optimization */ 
/* export const FILTER_ALERADY_SAVED_PRERENDERED_DATA = 'FILTER_ALERADY_SAVED_PRERENDERED_DATA' */
export const START_EMBED_IFRAME = 'START_EMBED_IFRAME'
export const SEARCH_KEYWORD = `SEARCH_KEYWORD`

export const ERROR_RESPONSE_WITH_MESSAGE = 'ERROR_RESPONSE_WITH_MESSAGE'
export const WALL_THEME_ID_UPDATE = 'WALL_THEME_ID_UPDATE'
//export const GET_EMBED_URL_DATA='GET_EMBED_URL_DATA'
export const GET_POST_DATA_SUCCESS_SEARCH = 'GET_POST_DATA_SUCCESS_SEARCH'
/* trial purpose for optimization */
/* export const GET_FILTERED_COMPLETE_POST_DATA_SUCCESS_SEARCH = 'GET_FILTERED_COMPLETE_POST_DATA_SUCCESS_SEARCH'*/

export const EMBED_URL_FETCHED = 'EMBED_URL_FETCHED' /*TO SAVE EMBED URL IN POST DATA REDUCER*/

export const GET_SEARCH_LOADER_SUCCESS = "GET_SEARCH_LOADER_SUCCESS";

export const UPDATE_REMOVE_DUPLICATE_FILTER = "UPDATE_REMOVE_DUPLICATE_FILTER";

export const UPDATE_POPUP_EXPIRE_IMAGE = "UPDATE_POPUP_EXPIRE_IMAGE";

export const RENDER_ID = 'RENDER_ID';